basic.showString("Hello!")
basic.forever(function () {
    for (let index = 0; index <= 4; index++) {
        led.plot(1, 0)
        basic.pause(100)
        led.plot(2, 0)
        basic.pause(150)
        led.plot(3, 0)
        basic.pause(200)
        led.plot(4, 1)
        basic.pause(250)
        led.plot(4, 2)
        basic.pause(300)
        led.plot(4, 3)
        basic.pause(350)
        led.plot(3, 4)
        basic.pause(400)
        led.plot(2, 4)
        basic.pause(450)
        led.plot(1, 4)
        basic.pause(500)
        led.plot(0, 3)
        basic.pause(550)
        led.plot(0, 2)
        basic.pause(560)
        led.plot(0, 1)
        basic.pause(570)
        led.plot(1, 2)
        basic.pause(580)
        led.plot(3, 2)
    }
})
